declare class Party implements Fighter {
    size: number;
    gold: number;
    blood: number;
    food: number;
    hunger: number;
    water: number;
    thirst: number;
    quests: number;
    questsCompleted: number;
    questPoints: number;
    damage: number;
    dealignmentProtection: number;
    strbase: number;
    dexbase: number;
    conbase: number;
    intbase: number;
    wisbase: number;
    chabase: number;
    strmod: number;
    dexmod: number;
    conmod: number;
    intmod: number;
    wismod: number;
    chamod: number;
    inventoryWeapon: EquipmentInventory;
    inventoryArmor: EquipmentInventory;
    weaponPoints: number;
    weaponConfig: Equipment;
    weapon: Equipment;
    armorPoints: number;
    armorConfig: Equipment;
    armor: Equipment;
    items: ItemInventory;
    status: Status;
    skills: Skills;
    constructor();
    get str(): number;
    get dex(): number;
    get con(): number;
    get int(): number;
    get wis(): number;
    get cha(): number;
    get health(): number;
}
